name: CI only

on:
  push:
    branches:
      - main

jobs:
  deploy-test-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3  
      with:
        deploy_key: ${{ secrets.PKEY }}
        external_repository: sInt3g3r/ToEnder-Deploy
        publish_branch: main
        publish_dir: ./frontend/src
